<script setup>
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { Mic, PhoneOff, Radio, X } from '@lucide/vue'
const props = defineProps({ sessionId:String, agent:Object, history:Array }); const emit=defineEmits(['close','transcript','assistant'])
const active=ref(false), status=ref('Connecting microphone...'), microphones=ref([]), selected=ref(localStorage.getItem('qwen-chat-microphone')||''), levels=ref(Array(24).fill(.1))
let stream,ctx,source,processor,asrId='',pcm=new Float32Array(0),sending=false,spoken=false,silence=0,ended=false,audioChain=Promise.resolve()
const join=(a,b)=>{const x=new Float32Array(a.length+b.length);x.set(a);x.set(b,a.length);return x}
function resample(a,rate){if(rate===16000)return a;const out=new Float32Array(Math.round(a.length*16000/rate));for(let i=0;i<out.length;i++){const p=i*rate/16000,j=Math.floor(p),n=Math.min(j+1,a.length-1);out[i]=a[j]*(1-p+j)+a[n]*(p-j)}return out}
async function devices(){microphones.value=(await navigator.mediaDevices.enumerateDevices()).filter(x=>x.kind==='audioinput');if(!microphones.value.some(x=>x.deviceId===selected.value))selected.value=microphones.value[0]?.deviceId||''}
function release(){processor?.disconnect();source?.disconnect();ctx?.close();stream?.getTracks().forEach(x=>x.stop());active.value=false}
async function chunk(){if(sending||!asrId||pcm.length<8000)return;sending=true;const part=pcm.slice(0,8000);pcm=pcm.slice(8000);try{const r=await fetch(`/api/chunk?session_id=${encodeURIComponent(asrId)}`,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:part.buffer}),j=await r.json();if(!r.ok)throw Error(j.error);if(j.text)emit('transcript',{text:j.text,partial:true})}catch(e){status.value=e.message;release()}finally{sending=false;if(active.value)chunk()}}
async function tts(text){const r=await fetch('/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,language:props.agent?.language||'Auto',speaker:props.agent?.voice||'Vivian'})});if(!r.ok)throw Error('TTS unavailable');const a=new Audio(URL.createObjectURL(await r.blob()));await a.play();await new Promise(resolve=>{a.onended=()=>{URL.revokeObjectURL(a.src);resolve()};a.onerror=()=>resolve()})}
function queueTts(text){audioChain=audioChain.catch(()=>{}).then(()=>tts(text));return audioChain}
async function turn(){if(!asrId||sending)return;status.value='Recognizing...';const r=await fetch(`/api/finish?session_id=${encodeURIComponent(asrId)}`,{method:'POST'}),j=await r.json();asrId='';pcm=new Float32Array(0);if(!j.text?.trim()){spoken=false;silence=0;status.value='Listening...';return}emit('transcript',{text:j.text.trim(),partial:false});status.value='Assistant is replying...';const response=await fetch('/api/agent/stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:j.text,conversation_id:props.sessionId,history:props.history||[],agent:props.agent})});const reader=response.body.getReader(),decoder=new TextDecoder();let raw='',reply='',spokenReply='';while(true){const {done,value}=await reader.read();if(done)break;raw+=decoder.decode(value,{stream:true});for(const line of raw.split('\n'))if(line.startsWith('data: ')){try{const piece=JSON.parse(line.slice(6)).text||'';if(piece&&!reply.endsWith(piece))reply+=piece}catch{}}emit('assistant',{text:reply,partial:true});const match=reply.slice(spokenReply.length).match(/^(.+?[。！？.!?])/);if(match){spokenReply+=match[1];queueTts(match[1])}}if(reply.slice(spokenReply.length))await queueTts(reply.slice(spokenReply.length));emit('assistant',{text:reply,partial:false});spoken=false;silence=0;status.value='Listening...'}
async function start(){try{await devices();stream=await navigator.mediaDevices.getUserMedia({audio:{...(selected.value?{deviceId:{exact:selected.value}}:{}),echoCancellation:true,noiseSuppression:true,autoGainControl:true}});if(ended)return release();ctx=new AudioContext();source=ctx.createMediaStreamSource(stream);processor=ctx.createScriptProcessor(4096,1,1);active.value=true;processor.onaudioprocess=async e=>{const input=e.inputBuffer.getChannelData(0),rms=Math.sqrt(input.reduce((s,x)=>s+x*x,0)/input.length);levels.value=levels.value.map((_,i)=>Math.max(.08,Math.min(1,Math.abs(input[(i*137)%input.length])*9)));pcm=join(pcm,resample(input,ctx.sampleRate));if(!asrId){const r=await fetch('/api/start',{method:'POST'});asrId=(await r.json()).session_id}if(rms>.012){spoken=true;silence=0}else if(spoken)silence+=input.length/ctx.sampleRate;chunk();if(spoken&&silence>.9&&!sending)turn()};source.connect(processor);processor.connect(ctx.destination);status.value='Listening...'}catch(e){status.value=`Microphone unavailable: ${e.message}`}}
function close(){ended=true;release();emit('close')};onMounted(start);onBeforeUnmount(close)
</script>
<template><section class="call-panel"><div class="call-heading"><div class="call-icon"><Radio :size="18" /></div><div><strong>Live phone call</strong><span>Audio is not recorded</span></div><button class="icon-button" type="button" aria-label="End call" @click="close"><X :size="17" /></button></div><label class="microphone-picker"><Mic :size="15"/><span>Microphone</span><select v-model="selected" :disabled="active" @change="localStorage.setItem('qwen-chat-microphone',selected)"><option v-for="(d,i) in microphones" :key="d.deviceId" :value="d.deviceId">{{ d.label||`Microphone ${i+1}` }}</option></select></label><div class="call-body"><div class="call-status"><span :class="{live:active}"/>{{status}}</div><div class="waveform" :class="{live:active}"><i v-for="(_,i) in levels" :key="i" :style="{height:`${4+levels[i]*27}px`}"/></div><button class="call-action stop" type="button" @click="close"><PhoneOff :size="18"/> End call</button></div></section></template>
