<script setup>
import { computed, reactive, watch } from 'vue'
import { Check, CopyPlus, Save, Trash2, X } from '@lucide/vue'
import { presetForProvider, PROVIDER_CATALOG } from '../lib/providerCatalog'
const props = defineProps({ models:Array, providers:Array, selectedModelId:String, busy:Boolean })
const emit = defineEmits(['close','save','delete','select'])
const empty=()=>({id:'',name:'',providerId:'deepseek',requestPath:'/chat/completions',model:'deepseek-chat',builtIn:false})
const draft=reactive(empty()), editing=computed(()=>Boolean(draft.id)), valid=computed(()=>draft.name.trim()&&draft.model.trim()&&draft.providerId)
const selectedProvider = computed(() => props.providers.find((provider) => provider.id === draft.providerId))
const providerPreset = computed(() => presetForProvider(selectedProvider.value))
const isCustom = computed(() => providerPreset.value === PROVIDER_CATALOG.custom)
const knownModels = computed(() => providerPreset.value.models)
function selectKnownModel() { const selected = knownModels.value.find((item) => item[1] === draft.model); if (selected) draft.name = selected[0] }
function edit(item){Object.assign(draft,empty(),item)} function resetModelForProvider(){ const first = presetForProvider(selectedProvider.value).models[0]; if (first) { draft.name = first[0]; draft.model = first[1] } else { draft.name = ''; draft.model = '' } } function create(){Object.assign(draft,empty(),{ providerId: props.providers[0]?.id || 'deepseek' }); resetModelForProvider() } function submit(){if(valid.value&&!props.busy)emit('save',{...draft,name:draft.name.trim(),model:draft.model.trim()})}
watch(()=>props.selectedModelId,id=>edit(props.models.find(x=>x.id===id)||props.models[0]||empty()),{immediate:true})
</script>
<template><Teleport to="body"><div class="modal-backdrop" @mousedown.self="$emit('close')"><section class="agent-modal" role="dialog" aria-modal="true"><header class="agent-modal-header"><div><h2>Models</h2><p>Known providers use their built-in model catalog; only Custom requires an identifier.</p></div><button class="icon-button" type="button" aria-label="Close models" @click="$emit('close')"><X :size="18"/></button></header><div class="agent-modal-layout"><aside class="agent-catalog"><button class="new-agent" type="button" @click="create"><CopyPlus :size="16"/> Add model</button><button v-for="item in models" :key="item.id" class="agent-list-item" :class="{active:draft.id===item.id}" type="button" @click="edit(item)"><span class="agent-avatar">M</span><span><strong>{{item.name}}</strong><small>{{providers.find(p=>p.id===item.providerId)?.name || 'Provider'}}</small></span><Check v-if="item.id===selectedModelId" :size="14"/></button></aside><form class="agent-form" @submit.prevent="submit"><div class="form-heading"><div><h3>{{editing?draft.name:'Choose model'}}</h3><p>{{ isCustom ? 'Enter the identifier supplied by your compatible endpoint.' : 'Choose an official model from the provider catalog.' }}</p></div><span v-if="draft.builtIn" class="built-in-label">Built-in</span></div><div class="field-grid two-columns"><label><span>Provider</span><select v-model="draft.providerId" :disabled="draft.builtIn" @change="resetModelForProvider"><option v-for="provider in providers" :key="provider.id" :value="provider.id">{{provider.name}}</option></select></label><label v-if="!isCustom"><span>Model</span><select v-model="draft.model" :disabled="draft.builtIn" @change="selectKnownModel"><option v-for="item in knownModels" :key="item[1]" :value="item[1]">{{item[0]}}</option></select></label><label v-else><span>Model identifier</span><input v-model="draft.model" required :disabled="draft.builtIn" placeholder="model-id"/></label><label><span>Display name</span><input v-model="draft.name" required :disabled="draft.builtIn" placeholder="Model name"/></label><label v-if="isCustom" class="full-width"><span>Request path</span><input v-model="draft.requestPath" :disabled="draft.builtIn" placeholder="/chat/completions"/></label></div><footer class="agent-form-actions"><button v-if="editing" class="secondary-action" type="button" @click="$emit('select',draft.id)">Use this model</button><button v-if="editing&&!draft.builtIn" class="danger-action" type="button" @click="$emit('delete',draft.id)"><Trash2 :size="16"/> Delete</button><button v-if="!draft.builtIn" class="primary-action" type="submit" :disabled="!valid||busy"><Save :size="16"/> {{editing?'Save model':'Add model'}}</button></footer></form></div></section></div></Teleport></template>
