<script setup>
import { computed, reactive, watch } from 'vue'
import { Check, CopyPlus, Save, Trash2, X } from '@lucide/vue'
const props = defineProps({ models:Array, selectedModelId:String, busy:Boolean })
const emit = defineEmits(['close','save','delete','select'])
const presets={openai:['OpenAI','https://api.openai.com/v1','gpt-5-mini'],anthropic:['Anthropic','https://api.anthropic.com','claude-sonnet-4-6'],google:['Google Gemini','https://generativelanguage.googleapis.com','gemini-2.5-flash'],deepseek:['DeepSeek','https://api.deepseek.com/v1','deepseek-chat'],dashscope:['Alibaba DashScope','https://dashscope.aliyuncs.com/compatible-mode/v1','qwen-plus'],moonshot:['Moonshot AI','https://api.moonshot.cn/v1','kimi-k2.5'],minimax:['MiniMax','https://api.minimax.io/v1','MiniMax-M2.1'],zhipu:['Zhipu AI','https://open.bigmodel.cn/api/paas/v4','glm-4.7'],siliconflow:['SiliconFlow','https://api.siliconflow.cn/v1','Qwen/Qwen3-235B-A22B'],openrouter:['OpenRouter','https://openrouter.ai/api/v1','openai/gpt-5-mini'],groq:['Groq','https://api.groq.com/openai/v1','llama-3.3-70b-versatile'],together:['Together AI','https://api.together.xyz/v1','meta-llama/Llama-3.3-70B-Instruct-Turbo'],fireworks:['Fireworks AI','https://api.fireworks.ai/inference/v1','accounts/fireworks/models/llama-v3p3-70b-instruct'],xai:['xAI','https://api.x.ai/v1','grok-3'],mistral:['Mistral AI','https://api.mistral.ai/v1','mistral-large-latest'],cohere:['Cohere','https://api.cohere.com/compatibility/v1','command-a-03-2025'],perplexity:['Perplexity','https://api.perplexity.ai','sonar-pro'],ollama:['Ollama (local)','http://127.0.0.1:11434/v1','qwen3:8b'],lmstudio:['LM Studio (local)','http://127.0.0.1:1234/v1','local-model'],vllm:['vLLM (local)','http://127.0.0.1:8000/v1','model'],custom:['Custom OpenAI-compatible','','']}
const empty=()=>({id:'',name:'',provider:'deepseek',baseUrl:'https://api.deepseek.com/v1',requestPath:'/chat/completions',apiKey:'',model:'deepseek-chat',builtIn:false})
const draft=reactive(empty()), editing=computed(()=>Boolean(draft.id)), valid=computed(()=>draft.name.trim()&&draft.model.trim()&&(draft.provider!=='custom'||draft.baseUrl.trim()))
function edit(item){Object.assign(draft,empty(),item)} function create(){Object.assign(draft,empty())} function applyPreset(){const p=presets[draft.provider];if(!p)return;draft.name=editing.value?draft.name:p[0];draft.baseUrl=p[1];draft.model=p[2]} function submit(){if(valid.value&&!props.busy)emit('save',{...draft,name:draft.name.trim(),model:draft.model.trim()})}
watch(()=>props.selectedModelId,id=>edit(props.models.find(x=>x.id===id)||props.models[0]||empty()),{immediate:true})
</script>
<template><Teleport to="body"><div class="modal-backdrop" @mousedown.self="$emit('close')"><section class="agent-modal" role="dialog" aria-modal="true"><header class="agent-modal-header"><div><h2>Model Settings</h2><p>Choose a provider preset or add an OpenAI-compatible endpoint.</p></div><button class="icon-button" type="button" aria-label="Close model settings" @click="$emit('close')"><X :size="18"/></button></header><div class="agent-modal-layout"><aside class="agent-catalog"><button class="new-agent" type="button" @click="create"><CopyPlus :size="16"/> New model</button><button v-for="item in models" :key="item.id" class="agent-list-item" :class="{active:draft.id===item.id}" type="button" @click="edit(item)"><span class="agent-avatar">M</span><span><strong>{{item.name}}</strong><small>{{item.provider}} · {{item.model}}</small></span><Check v-if="item.id===selectedModelId" :size="14"/></button></aside><form class="agent-form" @submit.prevent="submit"><div class="form-heading"><div><h3>{{editing?draft.name:'Create model'}}</h3><p>Provider catalog inspired by OpenCode and pi: connection details are reusable across Agents.</p></div><span v-if="draft.builtIn" class="built-in-label">Built-in</span></div><div class="field-grid two-columns"><label><span>Connection name</span><input v-model="draft.name" required :disabled="draft.builtIn" placeholder="e.g. DeepSeek production"/></label><label><span>Provider</span><select v-model="draft.provider" :disabled="draft.builtIn" @change="applyPreset"><option v-for="(_,id) in presets" :key="id" :value="id">{{presets[id][0]}}</option></select></label><label><span>Model</span><input v-model="draft.model" required :disabled="draft.builtIn" placeholder="Model identifier"/></label><label><span>API Key</span><input v-model="draft.apiKey" type="password" autocomplete="off" :disabled="draft.builtIn" placeholder="Stored locally"/></label><label class="full-width"><span>Base URL</span><input v-model="draft.baseUrl" :required="draft.provider==='custom'" type="url" :disabled="draft.builtIn" placeholder="https://api.example.com/v1"/></label><label class="full-width"><span>Request path</span><input v-model="draft.requestPath" :disabled="draft.builtIn" placeholder="/chat/completions"/></label></div><footer class="agent-form-actions"><button v-if="editing" class="secondary-action" type="button" @click="$emit('select',draft.id)">Use this model</button><button v-if="editing&&!draft.builtIn" class="danger-action" type="button" @click="$emit('delete',draft.id)"><Trash2 :size="16"/> Delete</button><button v-if="!draft.builtIn" class="primary-action" type="submit" :disabled="!valid||busy"><Save :size="16"/> {{editing?'Save model':'Create model'}}</button></footer></form></div></section></div></Teleport></template>
